name: flutter_scale_aware
description: A new Flutter package project.
version: 0.0.1
author: Jeremiah Ogbomo <jeremiahogbomo@gmail.com>
homepage: https://github.com/jogboms/flutter_screen_aware

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1
  test_coverage:
    git:
      url: https://github.com/jogboms/test-coverage.git
